name: ui_ecommerce
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_rating_bar: ^4.0.1
  badges: ^3.1.2
  curved_navigation_bar: ^1.0.6
  fancy_bottom_navigation: ^0.3.3
  clippy_flutter: ^2.0.0-nullsafety.1

flutter:
  uses-material-design: true

  assets:
    - images/1.jpg
    - images/2.jpg
    - images/3.jpg
    - images/4.jpg
    - images/google_icon.png
